"""
Generates css/file-icons.css and copies SVG icons from vscode-great-icons
and vscode-material-icon-theme.

Called by build-icons.sh — not intended to be run directly.
"""

import argparse
import json
import os
import shutil
from collections import defaultdict
from pathlib import Path


def find_svg(icon_name: str, great_dir: str, material_dir: str) -> str | None:
    """Find an SVG file for the given icon name, preferring great-icons."""
    for d in [great_dir, material_dir]:
        path = os.path.join(d, f"{icon_name}.svg")
        if os.path.isfile(path):
            return path
    return None


# Names in great-icons mapping that we know have different filenames
ICON_ALIASES = {
    "shell": ["console", "terminal", "shell"],
    "c-h": ["c-h", "h"],
    "cpp-h": ["cpp-h", "hpp"],
    "rlang": ["rlang", "r"],
    "react_alt": ["react_alt", "react-alt"],
}


def find_svg_with_aliases(icon_name: str, great_dir: str, material_dir: str) -> str | None:
    """Try the icon name and known aliases."""
    names = ICON_ALIASES.get(icon_name, [icon_name])
    if isinstance(names, str):
        names = [names]
    if icon_name not in names:
        names.insert(0, icon_name)
    for name in names:
        result = find_svg(name, great_dir, material_dir)
        if result:
            return result
    return None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--great-json", required=True)
    parser.add_argument("--great-icons", required=True)
    parser.add_argument("--material-icons", required=True)
    parser.add_argument("--out-icons", required=True)
    parser.add_argument("--out-css", required=True)
    args = parser.parse_args()

    with open(args.great_json, encoding="utf-8") as f:
        data = json.load(f)

    file_extensions = data.get("fileExtensions", {})
    file_names = data.get("fileNames", {})

    # -------------------------------------------------------------------------
    # 1. Collect all icons referenced and copy SVGs
    # -------------------------------------------------------------------------
    all_icon_names: set[str] = set()
    for icon in file_extensions.values():
        all_icon_names.add(icon.replace("_f_", ""))
    for icon in file_names.values():
        all_icon_names.add(icon.replace("_f_", ""))

    copied = 0
    missing = []
    for icon_name in sorted(all_icon_names):
        src = find_svg_with_aliases(icon_name, args.great_icons, args.material_icons)
        if src:
            dest = os.path.join(args.out_icons, f"{icon_name}.svg")
            shutil.copy2(src, dest)
            copied += 1
        else:
            missing.append(icon_name)

    # Also copy ALL SVGs from both repos (so we have the full library available)
    for src_dir in [args.great_icons, args.material_icons]:
        for f in Path(src_dir).glob("*.svg"):
            dest = os.path.join(args.out_icons, f.name)
            if not os.path.exists(dest):
                shutil.copy2(str(f), dest)
                copied += 1

    print(f"  Copied {copied} SVGs ({len(missing)} icons missing SVGs: {', '.join(missing[:10])}{'...' if len(missing) > 10 else ''})")

    # -------------------------------------------------------------------------
    # 2. Build extension → icon_name mapping, grouped by icon
    # -------------------------------------------------------------------------
    # Group extensions by their icon name for compact CSS
    icon_to_exts: dict[str, list[str]] = defaultdict(list)
    for ext, icon in sorted(file_extensions.items()):
        icon_name = icon.replace("_f_", "")
        # Skip if no SVG available
        if icon_name in missing:
            continue
        icon_to_exts[icon_name].append(ext)

    icon_to_names: dict[str, list[str]] = defaultdict(list)
    for name, icon in sorted(file_names.items()):
        icon_name = icon.replace("_f_", "")
        if icon_name in missing:
            continue
        icon_to_names[icon_name].append(name)

    # -------------------------------------------------------------------------
    # 3. Generate CSS
    # -------------------------------------------------------------------------
    lines: list[str] = []
    w = lines.append

    w("/*")
    w(" * File Icons — Custom SVG icons by file extension")
    w(" * AUTO-GENERATED by build-icons.sh — do not edit manually.")
    w(" *")
    w(" * Icons sourced from:")
    w(" *   - vscode-great-icons (MIT)")
    w(" *   - vscode-material-icon-theme (MIT)")
    w(" */")
    w("")

    # Base rule
    w("/* Base ::before dimensions */")
    w("tr.entry[data-entryname] td.name a::before {")
    w("    content: '';")
    w("    display: none;")
    w("    width: 16px;")
    w("    min-width: 16px;")
    w("    height: 16px;")
    w("    margin-right: 8px;")
    w("    vertical-align: -3px;")
    w("    background-size: contain;")
    w("    background-repeat: no-repeat;")
    w("    background-position: center;")
    w("}")
    w("")
    w("/* Hide all default octicon icons in file tree */")
    w("tr.entry[data-entryname] .octicon-file,")
    w("tr.entry[data-entryname] .octicon-file-directory-fill,")
    w("tr.entry[data-entryname] .octicon-file-submodule { display: none; }")
    w("")
    w("/* Default file icon */")
    w("tr.entry[data-entryname] td.name a::before {")
    w("    display: inline-block;")
    w("    background-image: url('/assets/icons/document.svg');")
    w("}")
    w("")
    w("/* Default folder icon */")
    w("tr.entry[data-entryname] td.name a:has(.octicon-file-directory-fill)::before,")
    w("tr.entry[data-entryname] td.name a:has(.octicon-file-submodule)::before {")
    w("    background-image: url('/assets/icons/folder.svg');")
    w("}")

    w("")

    def ext_selector(ext: str) -> str:
        """Build a CSS attribute selector for a file extension."""
        # Extensions that start with a dot are literal suffixes
        if ext.startswith("."):
            return f'tr.entry[data-entryname$="{ext}"]'
        # Check if it contains a dot (compound extension like blade.php, test.js)
        if "." in ext:
            return f'tr.entry[data-entryname$=".{ext}"]'
        # Simple extension
        return f'tr.entry[data-entryname$=".{ext}"]'

    def name_selector(name: str) -> str:
        """Build a CSS attribute selector for an exact filename."""
        return f'tr.entry[data-entryname="{name}"]'

    # Emit rules grouped by icon
    for icon_name in sorted(set(list(icon_to_exts.keys()) + list(icon_to_names.keys()))):
        exts = icon_to_exts.get(icon_name, [])
        names = icon_to_names.get(icon_name, [])
        if not exts and not names:
            continue

        # Build selector lists
        hide_selectors = []
        show_selectors = []

        for ext in exts:
            sel = ext_selector(ext)
            hide_selectors.append(f"{sel} .octicon-file")
            show_selectors.append(f"{sel} td.name a::before")

        for n in names:
            sel = name_selector(n)
            hide_selectors.append(f"{sel} .octicon-file")
            show_selectors.append(f"{sel} td.name a::before")

        # Write hide rule
        w(f"/* {icon_name} */")
        w(",\n".join(hide_selectors) + " { display: none; }")

        # Write show rule
        w(",\n".join(show_selectors) +
          f" {{ display: inline-block; background-image: url('/assets/icons/{icon_name}.svg'); }}")
        w("")

    # Write output
    css_content = "\n".join(lines)
    with open(args.out_css, "w", encoding="utf-8") as f:
        f.write(css_content)

    # Stats
    total_exts = sum(len(v) for v in icon_to_exts.values())
    total_names = sum(len(v) for v in icon_to_names.values())
    total_icons = len(set(list(icon_to_exts.keys()) + list(icon_to_names.keys())))
    print(f"  Generated CSS: {total_icons} icons, {total_exts} extensions, {total_names} named files")


if __name__ == "__main__":
    main()
